### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by pagaille**
"locales" package was missing, therefore gettext couldn't translate
updated pointer to roasariosis latest released version

### CODE REVIEW

**Comment by francoisjacquet** [comment]
Hello @pagaille 
Thank you for the PR.
Would you mind opening a Merge Request from [GitLab](https://gitlab.com/francoisjacquet/docker-rosariosis) next time?
GitHub is just a mirror for dockerhub. Thank you.

**Comment by francoisjacquet** [comment]
Hello @pagaille 

Did you have to manually add the locales and run `locale-gen`?
I stumbled upon these commands and was wondering if they needed to be added to the Dockerfile:
https://github.com/moodlehq/moodle-php-apache/blob/master/root/tmp/setup/php-extensions.sh#L37

**Comment by pagaille** [comment]
﻿Hi Francois,

It’s been a while already but as far as I can remember simply adding the package was enough. 

(About gitlabs I’m afraid it don’t even know what it is 😊)

Matthieu G.  (en mode mobile)

**Comment by francoisjacquet** [comment]
Ok, thank you.

**Pull request merged**
